python -m semantic_matching.train \
--encoder siamese_cbow \
--bert_model bert-base-chinese \
--with_negative \
--emb_dims 100 \
--max_len 30 \
--pooling mean \
--batch_size 1 \
--data_file data/train_neg.txt \
--save_dir output \
--epochs 1 \
--device cpu \
--workers 1
