python -m semantic_matching.train \
--encoder lstm \
--bert_model /data/bert_model/chinese_base \
--with_negative \
--emb_dims 100 \
--max_len 30 \
--pooling full_connection \
--batch_size 1 \
--data_file data/train_neg.txt \
--save_dir output \
--epochs 1 \
--device cpu \
--workers 1
